version: '3.1'

services:

  cache:
    container_name: redis_db
    image: "redis:latest"
    ports:
      - "6379:6379"

  db:
    container_name: postgres_db
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=19782003
  java-app:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=19782003
      - SPRING_DATA_REDIS_HOST=cache
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache