version: '3.1'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19782003
    ports:
        - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"